from enum import Enum

class Config(Enum):
    # MODBUS BAGLANTI AYARLARI
    MODBUS_IP= "10.10.1.50"
    MODBUS_PORT= 502

    SUNUCU_URL= "http://45.195.75.22:8099/api/data"
    WAIT_TIME= 2

    # MODBUS ADRESLERI
    MAKINE_HIZI=350 # REAL
    LAMINE_GERGINLIK_KG=200 # REAL
    LAMINASYON_SILINDIR_ISI_CELC=280 # REAL
    LAMINASYON_TEKNE_ISI_CELC=270 # REAL
    LAMINASYON_SAG_SIYIRICI_ISI_CELC=282 # REAL
    LAMINASYON_SOL_SIYIRICI_ISI_CELC=284 # REAL
    KUMAS_AYIRMA_BUTON=69 # BOOL

    KAYMAZ_1_SILINDIR_ISI_CELC=382 # REAL
    KAYMAZ_1_TEKNE_ISI_CELC=380 # REAL
    KAYMAZ_1_SAG_SIYIRICI_ISI_CELC=384 # REAL
    KAYMAZ_1_SOL_SIYIRICI_ISI_CELC=386 # REAL

    KAYMAZ_2_SILINDIR_ISI_CELC=396 # REAL
    KAYMAZ_2_TEKNE_ISI_CELC=394 # REAL
    KAYMAZ_2_SAG_SIYIRICI_ISI_CELC=398 # REAL
    KAYMAZ_2_SOL_SIYIRICI_ISI_CELC=400 # REAL